### ISSUE TITLE
Question about Room:GetEntities

### ISSUE THREAD

**Issue by laceous** [wofsauge/IsaacDocs#250]
The documentation says it's bugged, and to use Isaac.GetRoomEntities() instead.

Both loops seem to do the same thing:

```
local room = Game():GetRoom()
local roomEntities = room:GetEntities()
for i = 0, #roomEntities - 1 do
  local entity = roomEntities:Get(i)
  Isaac.DebugString('room: ' .. entity.Type .. '.' .. entity.Variant .. '.' .. entity.SubType)
end
```
```
for _, entity in ipairs(Isaac.GetRoomEntities()) do
  Isaac.DebugString('isaac: ' .. entity.Type .. '.' .. entity.Variant .. '.' .. entity.SubType)
end
```

Strangely, you can sometimes call Room:GetEntities():Get(i) past its bounds, but as long as you stay within bounds it seems like it works in the current Repentance patch.

Is this still bugged? Am I missing a use-case here?

**Comment by Zamiell** [comment]
i dont remember exactly what the bugs are.
but your code snippet showcases why we don't recommend that people ever use it: typing `local entity = roomEntities:Get(i)` is a complete waste of time, and confusing for other people reading the code

**Comment by amaurymaille** [comment]
`Isaac.GetRoomEntities()` will return a table that is a view of the entities in the room at the time the function was called, while `Room::GetEntities()` will return a userdata that stores a raw pointer to the array in memory that stores the entities in the room. Therefore, iterating over the return value of `Room::GetEntities()` will always iterate over the entities present in the room during the current logic frame, while iterating over the return value of `Isaac.GetRoomEntities()` will iterate over the entities that were present at the time the function was called.

I'm not sure if the array in memory is sized in such a way that it can store the max possible amount of each entity to avoid resizes, but that's the risk when working with `Room::GetEntities()`: since the userdata has a copy of the pointer to the array of entities in memory, if this pointer gets invalidated, which may happen without changing rooms (because resizes), the game may crash when iterating over the content of the userdata. With `Isaac.GetRoomEntities()`, the game may crash only if you manipulate the entities inside after changing rooms (maybe also if the entity has been removed since, but I don't know when the game actually frees the memory associated with an entity, maybe it is safe).

**Comment by wofsauge** [comment]
Ive improved the descriptions of both functions based on @amaurymaille `s post. Thank you very much for that cool explaination!

if anything other needs to be changed, please reopen the issue :)

Related commit: a877eb7c0805fd424ec1bb03023a45465945c332
